### ISSUE TITLE
No me deja migrar.

### ISSUE THREAD

**Issue by aranajhonny** [OswardJr/Zogan_Systems#1]
![captura de pantalla 2017-06-19 a las 21 55 57](https://user-images.githubusercontent.com/9091881/27313123-40db2596-553a-11e7-816e-4a6a8dd91043.png)

**Comment by OswardJr** [comment]
Cambiaste la clave en el .env?

**Comment by OswardJr** [comment]
Te paso la bd?

**Comment by aranajhonny** [comment]
igual no me va a dejar hacer nada.

**Comment by OswardJr** [comment]
resetea con el artisan y luego intenta migrar

**Comment by aranajhonny** [comment]
@OswardJr ya agarra pero mira lo que salió 
![captura de pantalla 2017-06-19 a las 22 10 53](https://user-images.githubusercontent.com/9091881/27313531-4fbd6068-553c-11e7-8c85-5ade55bf06b5.png)

**Comment by OswardJr** [comment]
php artisan make:auth?

**Comment by aranajhonny** [comment]
habia que aregar esto https://laravel-news.com/laravel-5-4-key-too-long-error

**Comment by OswardJr** [comment]
Primera vez que observo algo así o.o

**Comment by aranajhonny** [comment]
hay que hacerlo en la versión 5.4 por cierto aja que eras lo que me decias que era lento

**Comment by OswardJr** [comment]
Como andan las vistas allá? tardan? o es por la baja capacidad de la canaima?

**Comment by aranajhonny** [comment]
@OswardJr las vistas andan super mega rapido en 2 segundos ya esta todo perfectamente dibujado.
