### ISSUE TITLE
Datos de acceso

### ISSUE THREAD

**Issue by aranajhonny** [OswardJr/Zogan_Systems#10]
estoy por enviar un commit para hacer lo del inicio de sesión cuando migres tienes que entrar a la ruta /register para registrar usuario y cargas. este email admin@gandocam.com y la clave 123456

**Comment by aranajhonny** [comment]
con esto estoy habilitando la función de salir. 
![captura de pantalla 2017-07-11 a las 21 30 31](https://user-images.githubusercontent.com/9091881/28097832-910ccb12-6680-11e7-9199-434ccd94c985.png)

**Comment by aranajhonny** [comment]
@OswardJr  podrias actualizar tu copia local y decirme si funciona alla ?

**Comment by OswardJr** [comment]
voy

**Comment by OswardJr** [comment]
Funciona bien

**Comment by aranajhonny** [comment]
ok voy con lo otro
