### ISSUE TITLE
numero de orden de reparacion es estatico

### ISSUE THREAD

**Issue by aranajhonny** [OswardJr/Zogan_Systems#11]
Número: 0000001

hay que consultar el último número y sumarle 1. esto va a estar complejo

**Comment by OswardJr** [comment]
Wendy me dijo que no era necesario eso por ahora, pero podemos hacerlo

**Comment by aranajhonny** [comment]
listo. lo tengo algo básico pero esta bien.

**Comment by aranajhonny** [comment]
actualiza y pruebas debería salir el número 6 o lo que lleves.

**Comment by OswardJr** [comment]
nice
