### ISSUE TITLE
App Zogan

### ISSUE THREAD

**Issue by OswardJr** [OswardJr/Zogan_Systems#14]
Falta culminar la cita.
Añadir buscadores en los registros maestros para saber si existen dentro de la BD o no vía ajax.
Generar PDF y opción de descarga para la orden de reparación y citas.
Efectuarle algunas mejoras al proceso de orden de reparación,

Pendings:
Notificaciones por usuario logueado.
Notificaciones por correo.

@aranajhonny

**Comment by aranajhonny** [comment]
ok acabo de revisar vamos a ver si hay luz en la casa, cuando llegue
