### ISSUE TITLE
Errores de javascript.

### ISSUE THREAD

**Issue by aranajhonny** [OswardJr/Zogan_Systems#2]
Ve este error si le doy click a los menús laterales se encogen solos.

![errores](https://user-images.githubusercontent.com/9091881/27313842-227e87e2-553e-11e7-8271-79da9c2a9585.gif)

Es causado por esto.

![captura de pantalla 2017-06-19 a las 22 22 18](https://user-images.githubusercontent.com/9091881/27313858-38a8246a-553e-11e7-98da-aa8f4b4cc98c.png)

**Comment by aranajhonny** [comment]
@OswardJr  es en esa vista en los procesos el menú anda normal.

**Comment by OswardJr** [comment]
no me había fijado de ese erroe o.O

**Comment by OswardJr** [comment]
@aranajhonny Entonces es mi pc, de vaina anda :-1:

**Comment by aranajhonny** [comment]
ve 
![errores](https://user-images.githubusercontent.com/9091881/27314022-21603be8-553f-11e7-8096-fe45fe5af8bc.gif)

**Comment by OswardJr** [comment]
Vaya o.o

**Comment by aranajhonny** [comment]
con nginx anda mas rapido todavia.

**Comment by OswardJr** [comment]
y solventé lo del index

**Comment by aranajhonny** [comment]
estoy enviando cambios acuerdate de cada rato escribir esto. 

```bash
git fetch && git pull origin master
```

**Comment by aranajhonny** [comment]
solo falta arreglar eso de la vista.

**Comment by OswardJr** [comment]
listo

**Comment by aranajhonny** [comment]
estas trabajando en ubuntu ? or windows ?

**Comment by OswardJr** [comment]
win

**Comment by OswardJr** [comment]
Andan mucho mejor las vistas o.o en cuanto a rapidez

**Comment by aranajhonny** [comment]
mm si va. hablamos luego

**Comment by OswardJr** [comment]
sin errores en la consola, andamos ready

**Comment by OswardJr** [comment]
dale perro, activo

**Comment by OswardJr** [comment]
![wdw](https://user-images.githubusercontent.com/12636573/27315144-e3e380fc-5545-11e7-898c-77c4b6b9fa7c.png)
no había actualizado composer, act la pantalla de errors y warnings

**Comment by OswardJr** [comment]
![jj](https://user-images.githubusercontent.com/12636573/27318357-dfb38d42-5559-11e7-94cc-fe26bd559ba0.png)
cheque esto cuando puedas, si me atrae el id del corredor, pero el que tengo sesionado de la aseguradora en cuestión de asignar, no me lo está tomando xd

el save(); creo que no se puede ingresar, ya que no está incluído en la bd
o.O

**Comment by OswardJr** [comment]
listo
